#!/bin/bash
# Generate a production .env with fresh random secrets.
#
# Run once, on the production host, from the compose directory. Refuses to
# overwrite an existing .env — regenerating secrets against a live database
# would lock the backend out of its own data, so replacing one is a deliberate
# manual act, not something a re-run can do by accident.
#
# The Zitadel identifiers are left blank: they come from the Zitadel console
# after the project, application, and service user exist. See DEPLOY.md.
set -euo pipefail

cd "$(dirname "$0")/.."

# Both are required with no default. A default here is a trap: it would be one
# specific installation's hostname, so every other operator would generate a
# .env that looks complete and points at someone else's infrastructure. The
# external URL in particular fails silently when wrong — it is the address
# *Zitadel* calls, so no local health check ever exercises it.
: "${EXTERNAL_URL:?set EXTERNAL_URL to the public base URL Zitadel will POST to, e.g. https://syndra.example.org}"
: "${ZITADEL_DOMAIN:?set ZITADEL_DOMAIN to your Zitadel instance domain, e.g. auth.example.org}"

if [ -e .env ]; then
  echo "error: .env already exists in $(pwd)" >&2
  echo "       Regenerating would mint a new POSTGRES_PASSWORD that no longer" >&2
  echo "       matches the initialized database volume. Edit it by hand, or" >&2
  echo "       move it aside first if you genuinely want a clean slate." >&2
  exit 1
fi

command -v openssl >/dev/null || { echo "error: openssl not found" >&2; exit 1; }
secret() { openssl rand -hex 32; }

PG_PASSWORD="$(secret)"

umask 077
cat > .env <<EOF
# Syndra — production. Generated by scripts/gen-prod-env.sh.
# Never commit this file. Secrets below are unique to this host.

# --- Datastore ---
# DB_DSN is not set: docker-compose.yml derives it from POSTGRES_PASSWORD so
# the credential has one definition. Set DB_DSN only to point at an external
# database, and keep POSTGRES_PASSWORD in agreement if you do.
POSTGRES_PASSWORD=${PG_PASSWORD}
REDIS_URL=redis:6379

# --- Backend ---
PORT=8080
SYNDRA_API_KEY=$(secret)
MIGRATION_PATH=file:///app/db/migrations
CORS_ORIGIN=${EXTERNAL_URL}

# Explicitly off. Auto-detect would already skip seeding in live-Zitadel mode,
# but a production database should never depend on inference for whether it
# contains fixtures.
SYNDRA_SEED_DEMO=false

# --- Frontend ---
BACKEND_URL=http://backend:8080
NEXT_PUBLIC_API_URL=${EXTERNAL_URL}
# Distinct from SYNDRA_API_KEY so rotating the API key does not invalidate
# every live session cookie.
SESSION_SECRET=$(secret)

# --- Zitadel ---
# Base URL Zitadel POSTs to for Actions v2 targets. Must be reachable FROM
# Zitadel, which is why it is the public hostname and not the LXC IP.
SYNDRA_EXTERNAL_URL=${EXTERNAL_URL}
ZITADEL_DOMAIN=${ZITADEL_DOMAIN}
ZITADEL_ADMIN_ROLE_KEY=admin
ZITADEL_MACHINE_KEY_PATH=./zitadel-machine-key.json

# Fill from the Zitadel console — see DEPLOY.md step 4.
ZITADEL_AUDIENCE=
ZITADEL_CLIENT_ID=
# Fill after the first M2M call appears in the Zitadel event log. Until then
# the self-mutation loop guard is disabled and backend-initiated grant changes
# echo back through the event listener.
ZITADEL_M2M_USER_ID=

# Fill from \`make zitadel-actions-register\` output — see DEPLOY.md step 7.
# While blank, /api/action/inject and /api/webhooks/zitadel accept unsigned
# requests. Do not leave them blank once the host is publicly routable.
ZITADEL_ACTION_SIGNING_KEY=
ZITADEL_EVENT_SIGNING_KEY=
ZITADEL_ACTION_SIGNING_KEY_ROTATED_AT=
ZITADEL_ACTION_SIGNING_KEY_ROTATION_THRESHOLD_DAYS=90

# --- Sync service (profile: sync) ---
# Not started by default. Fill these in, then run:
#   docker compose --profile sync up -d
LLDAP_URL=
LLDAP_BIND_DN=
LLDAP_BIND_PASSWORD=
LLDAP_BASE_DN=
EOF

chmod 600 .env
echo "Wrote $(pwd)/.env (mode 600)."
echo
echo "Still required before \`docker compose up\`:"
echo "  - ZITADEL_AUDIENCE / ZITADEL_CLIENT_ID from the Zitadel application"
echo "  - ./zitadel-machine-key.json (service user key, chmod 600)"
